"""
Django settings for ulearn_vacs_project project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-v$ghmvh%_ms2ei5te@t)x#3$%ov3%5h%t(8ar-l%5@5haosxe4'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS = ["max01m.pythonanywhere.com"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'general_page',
    'general_stats_page',
    'relevance_page',
    'geography_page',
    'skills_page',
    'latest_vacs_page',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ulearn_vacs_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ulearn_vacs_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
# STATIC_ROOT = '/home/max01m/django/static' # For pythonanywhere (python manage.py collectstatic)
STATICFILES_DIRS = (os.path.join(BASE_DIR, 'static'),)

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')

DEFAULT_VAC_TEXT = r"""<p class="">
Добро пожаловать на главную страницу профессии специалиста по информационной безопасности! 
</p>

<p class="">
Информационная безопасность — одна из самых востребованных и стремительно развивающихся сфер IT. Её цель — защита данных, систем и инфраструктур от несанкционированного доступа, кибератак и утечек информации.
<p class="">
Как специалист по информационной безопасности, вы отвечаете за сохранность конфиденциальности, целостности и доступности информации в самых разных отраслях — от банковской сферы и государственных структур до IT-компаний и облачных сервисов. Ваша задача — выявлять уязвимости, минимизировать риски и строить надёжную стратегию киберзащиты.
</p>

<p class="">
В своей работе вы применяете современные инструменты: системы обнаружения вторжений (IDS/IPS), межсетевые экраны, средства шифрования, антивирусные решения и платформы управления инцидентами (SIEM). Вы можете проводить тесты на проникновение, аудит безопасности, следить за инцидентами и оперативно на них реагировать.</p>

<p class="">
Одним из ключевых направлений вашей деятельности становится разработка и внедрение политик безопасности, обучение персонала основам безопасной работы с информацией, а также соблюдение международных стандартов и нормативов — таких как ISO/IEC 27001, GDPR или ГОСТ.</p>

<p class="">
Вы тесно взаимодействуете с системными администраторами, разработчиками, аналитиками и руководством компании. Такая командная работа позволяет создать комплексную и эффективную систему защиты, способную оперативно реагировать на любые угрозы.</p>

<p class="">
Для успешной карьеры в ИБ необходимы не только технические навыки, но и аналитическое мышление, внимание к деталям, стрессоустойчивость и постоянное стремление к обучению — ведь киберугрозы постоянно эволюционируют.
Информационная безопасность — это не просто защита технологий. Это обеспечение устойчивости бизнеса и цифрового доверия пользователей. Вы — один из тех, кто делает цифровой мир безопаснее</p>"""
