# Generated by Django 5.1.4 on 2025-01-19 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vac_pic', models.ImageField(blank=True, default='static\\general\\images\\cybersec.png', null=True, upload_to='', verbose_name='Картинка вакансии')),
                ('vac_text', models.TextField(blank=True, default='\n<p class="">\n       ', null=True, verbose_name='Текст вакансии')),
            ],
            options={
                'verbose_name': 'Главная',
                'verbose_name_plural': 'Главная',
            },
        ),
    ]
